#!/usr/bin/env bash
set -eu

title() {
    printf "\n\033[1;37m%s\033[0m\n" "$1"
}

os="$(uname -s)"

title "Install Ansible"
case "$os" in
    Darwin)
        brew install ansible
        ;;
    Linux)
        sudo apt update
        sudo apt install python3-venv python3-pip -y
        python3 -m venv ~/ansible-venv
        # shellcheck disable=SC1090,SC1091
        source ~/ansible-venv/bin/activate
        pip install ansible
        ;;
    *)
        echo "Unsupported OS: $os" >&2
        exit 1
        ;;
esac

# Set GIT_REPO (and optionally GIT_BRANCH, default master) to install the role
# from an arbitrary git repo/branch instead of Ansible Galaxy. Handy for testing
# a branch before it is released.
GIT_REPO="${GIT_REPO:-}"
GIT_BRANCH="${GIT_BRANCH:-master}"

# When run from a checkout (CI / development) use this repo as the role,
# otherwise (curl | bash) pull the published role and playbook.
if [ -f ./playbook.yml ] && [ -f ./meta/main.yml ]; then
    title "Use local role checkout"
    roles_dir="$(mktemp -d)"
    ln -sfn "$PWD" "$roles_dir/viasite-ansible.zsh"
    export ANSIBLE_ROLES_PATH="$roles_dir"
    playbook=./playbook.yml
elif [ -n "$GIT_REPO" ]; then
    title "Clone viasite-ansible.zsh from $GIT_REPO ($GIT_BRANCH)"
    checkout_dir="$(mktemp -d)/viasite-ansible.zsh"
    git clone --depth 1 --branch "$GIT_BRANCH" "$GIT_REPO" "$checkout_dir"
    roles_dir="$(mktemp -d)"
    ln -sfn "$checkout_dir" "$roles_dir/viasite-ansible.zsh"
    export ANSIBLE_ROLES_PATH="$roles_dir"
    playbook="$checkout_dir/playbook.yml"
else
    title "Install viasite-ansible.zsh"
    ansible-galaxy install viasite-ansible.zsh --force

    title "Download playbook to /tmp/zsh.yml"
    curl -fsSL https://raw.githubusercontent.com/viasite-ansible/ansible-role-zsh/master/playbook.yml > /tmp/zsh.yml
    playbook=/tmp/zsh.yml
fi

# Avoid interactive prompts: only ask for the become password when sudo is not passwordless.
become=(-b)
if ! sudo -n true 2>/dev/null; then
    become=(-b -K)
fi

# Ansible's interpreter discovery can pick a version manager shim (asdf, pyenv,
# mise) that fails to execute, so pin the interpreter that runs ansible itself.
interpreter=()
ansible_shebang="$(head -n1 "$(command -v ansible)" 2>/dev/null | sed -e 's/^#!//' -e 's/[[:space:]].*//')"
case "$ansible_shebang" in
    /*/python*) interpreter=(-e "ansible_python_interpreter=$ansible_shebang") ;;
esac

# The role overwrites ~/.zshrc from its own template and only ever sources
# ~/.zshrc.local, so that is where a custom config has to live to survive.
zshrc="$HOME/.zshrc"
zshrc_local="$HOME/.zshrc.local"
backup_hint="Ansible keeps a backup next to it as ~/.zshrc.<random>.<pid>.<date>@<time>~"

if [ ! -s "$zshrc" ] || grep -q 'zshrc\.local' "$zshrc"; then
    : # absent, empty, or already generated by this role - nothing to preserve
elif [ -e "$zshrc_local" ]; then
    title "Warning: ~/.zshrc will be overwritten"
    echo "Your ~/.zshrc.local already exists and is left untouched, but anything kept"
    echo "only in ~/.zshrc is not carried over. $backup_hint"
# /dev/tty exists even with no controlling terminal, so only prompt if it opens.
elif { : < /dev/tty; } 2>/dev/null; then
    title "Move ~/.zshrc to ~/.zshrc.local?"
    echo "The role will overwrite ~/.zshrc. Moving it to ~/.zshrc.local keeps your"
    echo "config: the role sources that file and never touches it."
    printf "Move it? [Y/n] "
    read -r reply < /dev/tty || reply="n"
    case "$reply" in
        [nN]*) echo "Keeping ~/.zshrc as is, it will be overwritten. $backup_hint" ;;
        *) mv "$zshrc" "$zshrc_local" && echo "Moved to ~/.zshrc.local" ;;
    esac
else
    title "Warning: ~/.zshrc will be overwritten"
    echo "Move it to ~/.zshrc.local first to keep it: mv ~/.zshrc ~/.zshrc.local"
    echo "$backup_hint"
fi

title "Provision playbook for $(whoami)"
ansible-playbook -i "localhost," -c local "${become[@]}" ${interpreter[@]+"${interpreter[@]}"} "$playbook" --extra-vars="zsh_user=$(whoami)"

# Set ZSH_INSTALL_ROOT=1 to also provision the root user.
if [ "${ZSH_INSTALL_ROOT:-0}" = "1" ]; then
    title "Provision playbook for root"
    ansible-playbook -i "localhost," -c local "${become[@]}" ${interpreter[@]+"${interpreter[@]}"} "$playbook"
fi

title "Finished! Please, restart your shell."
echo ""
