---
- name: Install system packages
  become: false
  ansible.builtin.homebrew_cask:
    name:
      - iterm2
  when: ansible_system == 'Darwin'

- name: Create iTerm2 profile
  ansible.builtin.copy:
    src: iterm2_profile.json
    dest: "~/Library/Application Support/iTerm2/DynamicProfiles/{{ zsh_user }}-profile.json"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
    mode: u=rw,g=rw,o=rw
  when: ansible_os_family == 'Darwin'

- name: Create Powerlevel 10k config
  ansible.builtin.copy:
    src: p10k.zsh
    dest: "~{{ zsh_user }}/.p10k.zsh"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
    mode: u=rw,g=r,o=r

- name: Add .p10k.zsh to .zshrc.local
  when: user_profile_env_vars is defined
  loop: "{{ user_profile_env_vars }}"
  lineinfile:
    path: "~{{ zsh_user }}/.zshrc.local"
    #line: "[[ ! -f ~/.p10k.zsh ]] || source local"
    line: "source ~/.p10k.zsh"
    create: yes
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
    mode: u=rw,g=r,o=r

# add to ~/.zshrc_local for p10k auto prompt:
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

- name: Add env vars to user .zprofile
  when: zsh_zprofile_env_vars is defined and zsh_zprofile_env_vars|length > 0
  loop: "{{ zsh_zprofile_env_vars }}"
  lineinfile:
    path: "~{{ zsh_user }}/.zprofile"
    regexp: "^{{ item.split('=')[0] }}"
    line: "{{ item }}"
    create: yes
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
    mode: u=rw,g=r,o=r
