---
driver:
  name: docker
platforms:
  - name: ansible-role-zsh-ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true

verifier:
  name: testinfra

provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  inventory:
    group_vars:
      all:
        zsh_user: root
        zsh_theme: powerlevel10k
        zsh_mc_solarized_skin: true
        zsh_fzf_manage_opts_file: true
        zsh_antigen_bundles_extras:
          - { name: test/in-list, when: true }
          - { name: test/not-in-list, when: false }
          - { name: test/command-exists, command: zsh }
          - { name: test/command-not-exists, command: not-exists-commanddd }
